### ISSUE TITLE
Including sessionInfo and package versions

### ISSUE THREAD

**Issue by PeteHaitch** [Bioconductor/OrchestratingSingleCellAnalysis-release#8]
I'm using this book with a student and we couldn't quickly find the session info or package versions of the online version.
Did we miss it?

**Comment by LTLA** [comment]
Don't think they're there yet. The plan is to insert them as folded code chunks in the new vignettes.

**Comment by robertamezquita** [comment]
Sorry for the radio silence @PeteHaitch - sessionInfo has now been added to all the workflow chapters (I think!), let me know if you catch anything else missing!
